plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "log/**/*"

# Style preferences
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# Layout preferences
Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: true

# Metrics
Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

# Rails specific
Rails/FilePath:
  EnforcedStyle: arguments

Rails/TimeZone:
  EnforcedStyle: strict

Rails/Date:
  EnforcedStyle: strict

Rails/Output:
  Exclude:
    - "db/seeds.rb"
    - "lib/tasks/**/*"

# Performance
Performance/StringReplacement:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

# Optionally, you can configure or override rules here:
Capybara:
  Enabled: true

FactoryBot:
  Enabled: true

RSpec:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 15

RSpecRails:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true
